pipeline {
    agent {
        kubernetes {
            label 'mypod'
            yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: maven
    image: maven:3-alpine
    command: ["cat"]
    tty: true
"""
        }
        
    }
    stages {
        stage('Build') {
            steps {
                container('maven') {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                input('Do you want to proceed?')
                container('maven') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    container('maven') {
                        junit 'target/surefire-reports/*.xml'
                    }
                }
            }
        }
        
    }
}
